apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-pro-v3-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: platform-pro-v3.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: platform-pro-v3-service
            port:
              number: 80
